# Generated by Django 5.2.4 on 2025-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс рахунку'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_spending',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Витрати цього місяця'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Загальні витрати'),
        ),
    ]
