# Generated by Django 5.2.4 on 2025-07-29 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Нове замовлення'), ('order_status_changed', 'Зміна статусу замовлення'), ('payment_received', 'Отримано платіж'), ('low_stock', 'Низький залишок товару'), ('system', 'Системне сповіщення')], max_length=30, verbose_name='Тип сповіщення')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Додаткові дані')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Відправлено')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email відправлено')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Telegram відправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочитання')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name="Пов'язане замовлення")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'ordering': ['-created_at'],
            },
        ),
    ]
