# Generated by Django 5.2.4 on 2025-07-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Ключ сесії')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
                'unique_together': {('store', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер замовлення')),
                ('customer_name', models.CharField(max_length=200, verbose_name="Ім'я клієнта")),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email клієнта')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клієнта')),
                ('shipping_address', models.TextField(verbose_name='Адреса доставки')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Місто')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Поштовий індекс')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Підсумок')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість доставки')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Податок')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна сума')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Номер відстеження')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('failed', 'Помилка оплати'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус оплати')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Спосіб оплати')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакції')),
                ('source', models.CharField(choices=[('website', 'Веб-сайт'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('phone', 'Телефон')], default='website', max_length=20, verbose_name='Джерело замовлення')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('product_sku', models.CharField(blank=True, max_length=50, verbose_name='SKU товару')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна ціна')),
                ('variant_name', models.CharField(blank=True, max_length=100, verbose_name='Назва варіанту')),
                ('variant_value', models.CharField(blank=True, max_length=100, verbose_name='Значення варіанту')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant', verbose_name='Варіант')),
            ],
            options={
                'verbose_name': 'Товар замовлення',
                'verbose_name_plural': 'Товари замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано'), ('refunded', 'Повернено')], max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Історія статусу замовлення',
                'verbose_name_plural': 'Історія статусів замовлень',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='Кошик')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant', verbose_name='Варіант')),
            ],
            options={
                'verbose_name': 'Товар у кошику',
                'verbose_name_plural': 'Товари у кошику',
                'unique_together': {('cart', 'product', 'variant')},
            },
        ),
    ]
