# Generated by Django 5.2.4 on 2025-07-31 08:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_category_created_at_category_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактна особа')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='ІПН/ЄДРПОУ')),
                ('payment_terms', models.PositiveIntegerField(default=30, verbose_name='Умови оплати (днів)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('short_name', models.CharField(max_length=10, verbose_name='Скорочена назва')),
                ('is_base', models.BooleanField(default=False, verbose_name='Базова одиниця')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Одиниця вимірювання',
                'verbose_name_plural': 'Одиниці вимірювання',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('confirmed', 'Підтверджено'), ('in_transit', 'В дорозі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('movement_date', models.DateField(verbose_name='Дата переміщення')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
                ('reason', models.TextField(blank=True, verbose_name='Причина переміщення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_movements', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
            ],
            options={
                'verbose_name': 'Переміщення',
                'verbose_name_plural': 'Переміщення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Кількість в упаковці')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Штрих-код')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='products.product', verbose_name='Товар')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.unit', verbose_name='Одиниця вимірювання')),
            ],
            options={
                'verbose_name': 'Фасування',
                'verbose_name_plural': 'Фасування',
                'ordering': ['product', '-is_default', 'quantity'],
                'unique_together': {('product', 'unit', 'quantity')},
            },
        ),
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Кількість')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Отримана кількість')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.movement', verbose_name='Переміщення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.packaging', verbose_name='Фасування')),
            ],
            options={
                'verbose_name': 'Позиція переміщення',
                'verbose_name_plural': 'Позиції переміщення',
                'ordering': ['movement', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('confirmed', 'Підтверджено'), ('in_transit', 'В дорозі'), ('received', 'Отримано'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('order_date', models.DateField(verbose_name='Дата замовлення')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Очікувана дата')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Дата отримання')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна сума')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='warehouse.supplier', verbose_name='Постачальник')),
            ],
            options={
                'verbose_name': 'Постачання',
                'verbose_name_plural': 'Постачання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Кількість')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Отримана кількість')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ціна за одиницю')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна ціна')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.packaging', verbose_name='Фасування')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.supply', verbose_name='Постачання')),
            ],
            options={
                'verbose_name': 'Позиція постачання',
                'verbose_name_plural': 'Позиції постачання',
                'ordering': ['supply', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Завідувач')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supply',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='warehouse.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='movement',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='warehouse.warehouse', verbose_name='Склад відправлення'),
        ),
        migrations.AddField(
            model_name='movement',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='warehouse.warehouse', verbose_name='Склад призначення'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('in_progress', 'В процесі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('total_items_counted', models.PositiveIntegerField(default=0, verbose_name='Підраховано позицій')),
                ('total_discrepancy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна сума розбіжностей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Відповідальна особа')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Інвентаризація',
                'verbose_name_plural': 'Інвентаризації',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('reason', models.CharField(choices=[('expired', 'Прострочений'), ('damaged', 'Пошкоджений'), ('lost', 'Втрачений'), ('theft', 'Крадіжка'), ('defective', 'Брак'), ('other', 'Інше')], max_length=20, verbose_name='Причина')),
                ('writeoff_date', models.DateField(verbose_name='Дата списання')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна сума')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_writeoffs', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeoffs', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Списання',
                'verbose_name_plural': 'Списання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriteOffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Кількість')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Собівартість за одиницю')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна собівартість')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.packaging', verbose_name='Фасування')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('writeoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.writeoff', verbose_name='Списання')),
            ],
            options={
                'verbose_name': 'Позиція списання',
                'verbose_name_plural': 'Позиції списання',
                'ordering': ['writeoff', 'product'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Очікувана кількість')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Фактична кількість')),
                ('shortage_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Недостача')),
                ('surplus_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Излишок')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Собівартість за одиницю')),
                ('discrepancy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сума розбіжності')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('counted_at', models.DateTimeField(blank=True, null=True, verbose_name='Час підрахунку')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='Підраховано користувачем')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='warehouse.inventory', verbose_name='Інвентаризація')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.packaging', verbose_name='Фасування')),
            ],
            options={
                'verbose_name': 'Позиція інвентаризації',
                'verbose_name_plural': 'Позиції інвентаризації',
                'ordering': ['inventory', 'product'],
                'unique_together': {('inventory', 'product', 'packaging')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Кількість')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Зарезервована кількість')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Собівартість')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Мінімальний залишок')),
                ('max_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Максимальний залишок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.packaging', verbose_name='Фасування')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Залишок',
                'verbose_name_plural': 'Залишки',
                'ordering': ['warehouse', 'product'],
                'unique_together': {('warehouse', 'product', 'packaging')},
            },
        ),
    ]
