# Generated by Django 5.2.4 on 2025-07-31 08:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_created_at_category_updated_at'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('method', models.CharField(choices=[('fifo', 'FIFO - Перший прийшов, перший пішов'), ('lifo', 'LIFO - Останній прийшов, перший пішов'), ('average', 'Середньозважена собівартість'), ('specific', 'Конкретна ідентифікація')], max_length=20, unique=True, verbose_name='Метод')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Метод розрахунку собівартості',
                'verbose_name_plural': 'Методи розрахунку собівартості',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateTimeField(verbose_name='Дата розрахунку')),
                ('total_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Загальна кількість')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Середня собівартість')),
                ('fifo_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='FIFO собівартість')),
                ('lifo_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='LIFO собівартість')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна вартість')),
                ('batches_count', models.PositiveIntegerField(default=0, verbose_name='Кількість партій')),
                ('is_current', models.BooleanField(default=True, verbose_name='Поточний розрахунок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.packaging', verbose_name='Фасування')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_calculations', to='products.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_calculations', to='warehouse.warehouse', verbose_name='Склад')),
                ('costing_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.costingmethod', verbose_name='Метод розрахунку')),
            ],
            options={
                'verbose_name': 'Розрахунок собівартості',
                'verbose_name_plural': 'Розрахунки собівартості',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Номер партії')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Початкова кількість')),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Залишок партії')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Собівартість за одиницю')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна собівартість партії')),
                ('received_date', models.DateTimeField(verbose_name='Дата надходження')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Термін придатності')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.packaging', verbose_name='Фасування')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='products.product', verbose_name='Товар')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='warehouse.supplier', verbose_name='Постачальник')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='warehouse.supply', verbose_name='Постачання')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Партія товару',
                'verbose_name_plural': 'Партії товарів',
                'ordering': ['warehouse', 'product', 'received_date'],
                'unique_together': {('warehouse', 'product', 'packaging', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Надходження'), ('out', 'Витрата'), ('transfer_in', 'Переміщення (надходження)'), ('transfer_out', 'Переміщення (витрата)'), ('adjustment_in', 'Коригування (збільшення)'), ('adjustment_out', 'Коригування (зменшення)'), ('writeoff', 'Списання'), ('inventory', 'Інвентаризація')], max_length=20, verbose_name='Тип руху')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Собівартість за одиницю')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Загальна собівартість')),
                ('reference_document', models.CharField(blank=True, max_length=100, verbose_name='Документ-підстава')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID документа')),
                ('movement_date', models.DateTimeField(verbose_name='Дата руху')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='warehouse.stockbatch', verbose_name='Партія')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.packaging', verbose_name='Фасування')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Рух товару',
                'verbose_name_plural': 'Рух товарів',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Пріоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costing_rules', to='products.category', verbose_name='Категорія')),
                ('costing_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='warehouse.costingmethod', verbose_name='Метод розрахунку')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costing_rules', to='products.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costing_rules', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Правило розрахунку собівартості',
                'verbose_name_plural': 'Правила розрахунку собівартості',
                'ordering': ['warehouse', '-priority'],
                'unique_together': {('warehouse', 'category', 'costing_method'), ('warehouse', 'product', 'costing_method')},
            },
        ),
    ]
