# Generated by Django 5.2.4 on 2025-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_costingmethod_costcalculation_stockbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='scan_method',
            field=models.CharField(choices=[('manual', 'Ручне введення'), ('barcode', 'Штрихкод'), ('qr_code', 'QR код')], default='manual', max_length=20, verbose_name='Метод сканування'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='scanned_barcode',
            field=models.CharField(blank=True, help_text='Штрихкод, який був відсканований під час інвентаризації', max_length=13, verbose_name='Відсканований штрихкод'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='scanned_qr_code',
            field=models.CharField(blank=True, help_text='QR код, який був відсканований під час інвентаризації', max_length=100, verbose_name='Відсканований QR код'),
        ),
    ]
