# Generated by Django 5.2.4 on 2025-07-31 08:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_created_at_category_updated_at'),
        ('warehouse', '0002_costingmethod_costcalculation_stockbatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='auto_pricing',
            field=models.BooleanField(default=False, help_text='Автоматично розраховувати ціну на основі собівартості та націнки', verbose_name='Автоматичне ціноутворення'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Орієнтовна собівартість для розрахунків (якщо не використовується автоматичний розрахунок)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Базова собівартість'),
        ),
        migrations.AddField(
            model_name='product',
            name='costing_method',
            field=models.ForeignKey(blank=True, help_text='Якщо не вказано, використовується метод за замовчуванням', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='warehouse.costingmethod', verbose_name='Метод розрахунку собівартості'),
        ),
        migrations.AddField(
            model_name='product',
            name='critical_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Критична кількість для терміновго поповнення', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Критичний поріг залишків'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_cost_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Останнє оновлення собівартості'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Мінімальна кількість для попередження про малі залишки', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Поріг малих залишків'),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Відсоток націнки до собівартості', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Націнка (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Максимальна кількість замовлення'),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Мінімальна кількість замовлення'),
        ),
        migrations.AddField(
            model_name='product',
            name='optimal_stock_level',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Цільова кількість для підтримки на складі', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Оптимальний рівень запасів'),
        ),
        migrations.AddField(
            model_name='product',
            name='order_increment',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='Кратність, на яку може збільшуватися кількість замовлення', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Крок замовлення'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_update_frequency',
            field=models.CharField(choices=[('manual', 'Вручну'), ('daily', 'Щодня'), ('weekly', 'Щотижня'), ('on_cost_change', 'При зміні собівартості')], default='manual', max_length=20, verbose_name='Частота оновлення ціни'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'В наявності'), ('out_of_stock', 'Немає в наявності'), ('limited', 'Обмежена кількість'), ('preorder', 'Під замовлення'), ('discontinued', 'Знято з виробництва')], default='in_stock', max_length=20, verbose_name='Статус наявності'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Увімкнути облік залишків на складах', verbose_name='Відстежувати залишки'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cost_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Додаткова собівартість для цього варіанту', max_digits=10, verbose_name='Доплата до собівартості'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku_suffix',
            field=models.CharField(blank=True, max_length=20, verbose_name='Суфікс SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_backorders',
            field=models.BooleanField(default=False, help_text='Дозволити замовлення при відсутності на складі', verbose_name='Дозволити попереднє замовлення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Акційна ціна'),
        ),
    ]
