# Generated by Django 5.2.4 on 2025-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_is_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_generate_codes',
            field=models.BooleanField(default=True, help_text='Автоматично генерувати штрихкод і QR код', verbose_name='Автогенерація кодів'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='13 цифр для поштучного товару, 7 цифр для вагового', max_length=13, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('piece', 'Поштучний товар'), ('weight', 'Ваговий товар')], default='piece', max_length=10, verbose_name='Тип товару'),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.CharField(blank=True, help_text='Унікальний QR код товару', max_length=100, unique=True, verbose_name='QR код'),
        ),
    ]
