# Generated by Django 5.2.4 on 2025-07-31 11:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_auto_generate_codes_product_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='auto_pricing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='critical_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_cost_update',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='markup_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='optimal_stock_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_update_frequency',
        ),
        migrations.AlterField(
            model_name='product',
            name='base_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Резервна собівартість (основний розрахунок через warehouse та прайс-листи)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Базова собівартість'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Поточна ціна продажу (синхронізується з прайс-листів)', max_digits=10, verbose_name='Ціна продажу'),
        ),
    ]
