# Generated by Django 5.2.4 on 2025-08-01 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_unused_pricing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allow_backorders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='auto_generate_codes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='track_stock',
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('piece', 'Поштучний товар'), ('weight', 'Ваговий товар')], default='piece', max_length=10, verbose_name='Тип товару')),
                ('barcode', models.CharField(blank=True, help_text='13 цифр для поштучного товару, 7 цифр для вагового', max_length=13, unique=True, verbose_name='Штрихкод')),
                ('qr_code', models.CharField(blank=True, help_text='Унікальний QR код товару', max_length=100, unique=True, verbose_name='QR код')),
                ('auto_generate_codes', models.BooleanField(default=True, help_text='Автоматично генерувати штрихкод і QR код', verbose_name='Автогенерація кодів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_info', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Штрихкод товару',
                'verbose_name_plural': 'Штрихкоди товарів',
            },
        ),
        migrations.CreateModel(
            name='ProductSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta keywords')),
                ('og_title', models.CharField(blank=True, max_length=95, verbose_name='OG title')),
                ('og_description', models.CharField(blank=True, max_length=300, verbose_name='OG description')),
                ('og_image', models.ImageField(blank=True, upload_to='og_images/', verbose_name='OG зображення')),
                ('noindex', models.BooleanField(default=False, verbose_name='No Index')),
                ('nofollow', models.BooleanField(default=False, verbose_name='No Follow')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'SEO налаштування товару',
                'verbose_name_plural': 'SEO налаштування товарів',
            },
        ),
    ]
