# Generated by Django 5.2.4 on 2025-08-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_allow_backorders_and_more'),
    ]

    operations = [
        # Видаляємо зв'язок category з Product
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        # Видаляємо модель Category
        migrations.DeleteModel(
            name='Category',
        ),
    ]
