# Generated by Django 5.2.4 on 2025-08-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20250804_1457'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='category_images/', verbose_name='Зображення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name'],
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категорія'),
        ),
    ]
