# Generated by Django 5.2.4 on 2025-07-31 11:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_remove_unused_pricing_fields'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Назва прайс-листа')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('pricing_strategy', models.CharField(choices=[('manual', 'Ручне встановлення цін'), ('cost_plus_markup', 'Собівартість + націнка'), ('competitor_based', 'На основі цін конкурентів'), ('value_based', 'Цінова стратегія на основі цінності'), ('dynamic', 'Динамічне ціноутворення')], default='cost_plus_markup', max_length=20, verbose_name='Стратегія ціноутворення')),
                ('default_markup_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999.99'))], verbose_name='Націнка за замовчуванням (%)')),
                ('default_markup_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Фіксована націнка за замовчуванням')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('auto_update_from_cost', models.BooleanField(default=False, verbose_name='Автоматично оновлювати з собівартості')),
                ('update_frequency', models.CharField(choices=[('manual', 'Вручну'), ('daily', 'Щодня'), ('weekly', 'Щотижня'), ('monthly', 'Щомісяця'), ('on_cost_change', 'При зміні собівартості'), ('on_supply', 'При постачанні')], default='manual', max_length=20, verbose_name='Частота оновлення')),
                ('last_cost_sync', models.DateTimeField(blank=True, null=True, verbose_name='Остання синхронізація собівартості')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Діє з')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Діє до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_price_lists', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листи',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BulkPriceUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Назва операції')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('update_type', models.CharField(choices=[('by_category', 'За категорією'), ('by_supplier', 'За постачальником'), ('by_selection', 'Вибрані товари'), ('all_products', 'Всі товари в прайс-листі'), ('price_range', 'За діапазоном цін'), ('markup_adjustment', 'Коригування націнки')], max_length=20, verbose_name='Тип оновлення')),
                ('adjustment_type', models.CharField(choices=[('percentage', 'Відсоток'), ('fixed_amount', 'Фіксована сума'), ('set_markup', 'Встановити націнку'), ('set_price', 'Встановити ціну')], max_length=20, verbose_name='Тип коригування')),
                ('adjustment_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Значення коригування')),
                ('min_current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мінімальна поточна ціна')),
                ('max_current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальна поточна ціна')),
                ('is_executed', models.BooleanField(default=False, verbose_name='Виконано')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Час виконання')),
                ('affected_items_count', models.PositiveIntegerField(default=0, verbose_name='Змінено позицій')),
                ('execution_log', models.TextField(blank=True, verbose_name='Лог виконання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('categories', models.ManyToManyField(blank=True, to='products.category', verbose_name='Категорії')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('selected_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Вибрані товари')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_updates', to='pricelists.pricelist', verbose_name='Прайс-лист')),
            ],
            options={
                'verbose_name': 'Масове оновлення цін',
                'verbose_name_plural': 'Масові оновлення цін',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_calculation_method', models.CharField(choices=[('auto', 'Автоматично з warehouse'), ('manual', 'Ручне введення'), ('last_supply', 'З останнього постачання'), ('average_supply', 'Середнє по постачанням')], default='auto', max_length=20, verbose_name='Метод розрахунку собівартості')),
                ('manual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ручна собівартість')),
                ('calculated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Розрахована собівартість')),
                ('markup_type', models.CharField(choices=[('percentage', 'Відсоток від собівартості'), ('fixed_amount', 'Фіксована сума'), ('fixed_price', 'Фіксована ціна'), ('formula', 'Формула розрахунку')], default='percentage', max_length=20, verbose_name='Тип націнки')),
                ('markup_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Значення націнки')),
                ('markup_formula', models.TextField(blank=True, help_text='Приклад: cost * 1.5 + 10 (доступні змінні: cost, category_markup)', verbose_name='Формула розрахунку')),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Розрахована ціна')),
                ('manual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ручна ціна')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Фінальна ціна')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Мінімальна ціна')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Максимальна ціна')),
                ('is_manual_override', models.BooleanField(default=False, help_text='Ціна встановлена вручну і не буде автоматично оновлюватися', verbose_name='Ручне перевизначення')),
                ('exclude_from_auto_update', models.BooleanField(default=False, verbose_name='Виключити з автооновлення')),
                ('last_cost_update', models.DateTimeField(blank=True, null=True, verbose_name='Останнє оновлення собівартості')),
                ('last_price_update', models.DateTimeField(blank=True, null=True, verbose_name='Останнє оновлення ціни')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(blank=True, help_text='Автоматично заповнюється з товару', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категорія')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricelists.pricelist', verbose_name='Прайс-лист')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція прайс-листа',
                'verbose_name_plural': 'Позиції прайс-листа',
                'ordering': ['product__name'],
                'unique_together': {('price_list', 'product')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара собівартість')),
                ('new_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Нова собівартість')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Нова ціна')),
                ('change_reason', models.CharField(choices=[('manual', 'Ручна зміна'), ('cost_update', 'Оновлення собівартості'), ('bulk_update', 'Масове оновлення'), ('supply', 'Постачання'), ('competitor_price', 'Зміна цін конкурентів'), ('seasonal', 'Сезонна зміна'), ('promotion', 'Акція')], default='manual', max_length=20, verbose_name='Причина зміни')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Час зміни')),
                ('bulk_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricelists.bulkpriceupdate', verbose_name='Масове оновлення')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Змінено користувачем')),
                ('price_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='pricelists.pricelistitem', verbose_name='Позиція прайс-листа')),
            ],
            options={
                'verbose_name': 'Історія зміни ціни',
                'verbose_name_plural': 'Історія зміни цін',
                'ordering': ['-changed_at'],
            },
        ),
    ]
