# Generated by Django 5.2.4 on 2025-08-01 11:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Фінальна ціна'),
        ),
    ]
