# Generated by Django 5.2.4 on 2025-07-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('yookassa', 'ЮKassa'), ('cash', 'Накладений платіж'), ('bank_transfer', 'Банківський переказ')], max_length=20, verbose_name='Спосіб оплати')),
                ('status', models.CharField(choices=[('pending', 'Очікує оплати'), ('processing', 'В обробці'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('cancelled', 'Скасовано'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус')),
                ('external_payment_id', models.CharField(blank=True, max_length=100, verbose_name='Зовнішній ID платежу')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакції')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метадані')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплати')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
    ]
