# Generated by Django 5.2.4 on 2025-08-04 07:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума повернення')),
                ('reason', models.TextField(verbose_name='Причина повернення')),
                ('status', models.CharField(choices=[('pending', 'Очікує обробки'), ('processing', 'В обробці'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('external_refund_id', models.CharField(blank=True, max_length=100, verbose_name='Зовнішній ID повернення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обробки')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ініціатор повернення')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Платіж')),
            ],
            options={
                'verbose_name': 'Повернення коштів',
                'verbose_name_plural': 'Повернення коштів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('yookassa', 'ЮKassa'), ('cash', 'Накладений платіж'), ('bank_transfer', 'Банківський переказ')], max_length=20, verbose_name='Тип методу оплати')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('display_name', models.CharField(max_length=100, verbose_name='Назва для відображення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('api_credentials', models.JSONField(blank=True, default=dict, help_text='Зберігаються в зашифрованому вигляді', verbose_name='API налаштування')),
                ('commission_type', models.CharField(choices=[('percentage', 'Відсоток'), ('fixed', 'Фіксована сума'), ('combined', 'Відсоток + фіксована сума')], default='percentage', max_length=10, verbose_name='Тип комісії')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Відсоток комісії')),
                ('commission_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Фіксована комісія')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мінімальна сума')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальна сума')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('icon', models.ImageField(blank=True, upload_to='payment_icons/', verbose_name='Іконка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Метод оплати',
                'verbose_name_plural': 'Методи оплати',
                'ordering': ['sort_order', 'display_name'],
                'unique_together': {('store', 'method_type')},
            },
        ),
    ]
