# Generated by Django 5.2.4 on 2025-07-29 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва магазину')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL магазину')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('logo', models.ImageField(blank=True, upload_to='store_logos/', verbose_name='Логотип')),
                ('banner_image', models.ImageField(blank=True, upload_to='store_banners/', verbose_name='Банер')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Основний колір')),
                ('secondary_color', models.CharField(default='#1F2937', max_length=7, verbose_name='Додатковий колір')),
                ('accent_color', models.CharField(default='#F59E0B', max_length=7, verbose_name='Акцентний колір')),
                ('show_instagram_feed', models.BooleanField(default=False, verbose_name='Показувати Instagram стрічку')),
                ('show_telegram_button', models.BooleanField(default=True, verbose_name='Показувати кнопку Telegram')),
                ('custom_css', models.TextField(blank=True, verbose_name='Кастомний CSS')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазини',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('block_type', models.CharField(choices=[('about', 'Про нас'), ('contact', 'Контакти'), ('faq', 'Часті питання'), ('custom', 'Кастомний блок')], default='custom', max_length=20, verbose_name='Тип блоку')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Блок магазину',
                'verbose_name_plural': 'Блоки магазину',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoreSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('website', 'Веб-сайт')], max_length=20, verbose_name='Тип соцмережі')),
                ('url', models.URLField(verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Назва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Соціальна мережа',
                'verbose_name_plural': 'Соціальні мережі',
                'unique_together': {('store', 'social_type')},
            },
        ),
    ]
