# Generated by Django 5.2.4 on 2026-02-16 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_category_product_category'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_user_id', models.CharField(max_length=100, unique=True)),
                ('instagram_username', models.CharField(max_length=150)),
                ('instagram_name', models.CharField(max_length=150)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('personal', 'Особистий'), ('business', 'Бізнес')], default='personal', max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Підключено'), ('disconnected', 'Відключено'), ('token_expired', 'Токен закінчився')], default='disconnected', max_length=20)),
                ('followers_count', models.IntegerField(default=0)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('auto_post_products', models.BooleanField(default=False)),
                ('hashtags', models.CharField(blank=True, max_length=500)),
                ('auto_respond_enabled', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to='stores.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Акаунт',
                'verbose_name_plural': 'Instagram Акаунти',
                'db_table': 'instagram_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramAutoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_template', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('posted', 'Опубліковано'), ('failed', 'Помилка')], default='pending', max_length=20)),
                ('instagram_post_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_posts', to='core.instagramaccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Instagram Автопост',
                'verbose_name_plural': 'Instagram Автопости',
                'db_table': 'instagram_auto_posts',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramDMKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('response_message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('times_triggered', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_keywords', to='core.instagramaccount')),
            ],
            options={
                'verbose_name': 'Instagram DM Ключове слово',
                'verbose_name_plural': 'Instagram DM Ключові слова',
                'db_table': 'instagram_dm_keywords',
            },
        ),
        migrations.CreateModel(
            name='InstagramDMMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_message_id', models.CharField(max_length=100, unique=True)),
                ('sender_username', models.CharField(max_length=150)),
                ('sender_id', models.CharField(max_length=100)),
                ('message_text', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('auto_response_sent', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_messages', to='core.instagramaccount')),
            ],
            options={
                'verbose_name': 'Instagram DM Повідомлення',
                'verbose_name_plural': 'Instagram DM Повідомлення',
                'db_table': 'instagram_dm_messages',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=100, unique=True)),
                ('post_type', models.CharField(choices=[('image', 'Зображення'), ('video', 'Відео'), ('carousel', 'Карусель')], max_length=20)),
                ('media_url', models.URLField()),
                ('caption', models.TextField(blank=True)),
                ('permalink', models.URLField()),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('posted_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.instagramaccount')),
                ('related_products', models.ManyToManyField(blank=True, related_name='instagram_posts', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to='stores.store')),
            ],
            options={
                'verbose_name': 'Instagram Пост',
                'verbose_name_plural': 'Instagram Пости',
                'db_table': 'instagram_posts',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_followers', models.IntegerField(default=0)),
                ('total_followers', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('posts_published', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.instagramaccount')),
            ],
            options={
                'verbose_name': 'Instagram Статистика',
                'verbose_name_plural': 'Instagram Статистики',
                'db_table': 'instagram_statistics',
                'ordering': ['-date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
