# Generated by Django 5.2.4 on 2026-02-16 15:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('feature_type', models.CharField(choices=[('boolean', 'Так/Ні'), ('numeric', 'Число'), ('text', 'Текст')], default='boolean', max_length=20, verbose_name='Тип особливості')),
                ('default_value', models.CharField(blank=True, max_length=255, verbose_name='Значення за замовчуванням')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Особливість плану',
                'verbose_name_plural': 'Особливості плану',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва плану')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Щомісячно'), ('yearly', 'Щорічно')], default='monthly', max_length=20, verbose_name='Цикл біллінгу')),
                ('max_stores', models.IntegerField(default=1, verbose_name='Максимум магазинів')),
                ('max_products', models.IntegerField(default=100, verbose_name='Максимум товарів')),
                ('max_monthly_orders', models.IntegerField(default=1000, verbose_name='Макс. замовлень/місяць')),
                ('has_analytics', models.BooleanField(default=False, verbose_name='Аналітика')),
                ('has_email_support', models.BooleanField(default=False, verbose_name='Email підтримка')),
                ('has_priority_support', models.BooleanField(default=False, verbose_name='Пріоритетна підтримка')),
                ('has_custom_domain', models.BooleanField(default=False, verbose_name='Кастомний домен')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='API доступ')),
                ('has_integrations', models.BooleanField(default=False, verbose_name='Інтеграції')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Комісія з продажів (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендований')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'План підписки',
                'verbose_name_plural': 'План підписки',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Скасована'), ('suspended', 'Призупинена'), ('expired', 'Закінчена')], default='active', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата початку')),
                ('expires_at', models.DateTimeField(verbose_name='Дата закінчення')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата скасування')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Subscription ID')),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='Наступна дата биллінгу')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.subscriptionplan', verbose_name='План')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Підписка користувача',
                'verbose_name_plural': 'Підписки користувачів',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Invoice ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакції')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплати')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.usersubscription', verbose_name='Підписка')),
            ],
            options={
                'verbose_name': 'Платіж за підписку',
                'verbose_name_plural': 'Платежі за підписку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planfeature', verbose_name='Особливість')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='core.subscriptionplan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Значення особливості плану',
                'verbose_name_plural': 'Значення особливостей плану',
                'unique_together': {('plan', 'feature')},
            },
        ),
    ]
