# Generated by Django 5.2.4 on 2026-02-16 15:08

from decimal import Decimal
from django.db import migrations


def seed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("core", "SubscriptionPlan")

    SubscriptionPlan.objects.get_or_create(
        slug="free",
        defaults={
            "name": "Безкоштовний",
            "description": "Ідеальний для початку. Базовий функціонал для одного магазину.",
            "price": Decimal("0.00"),
            "billing_cycle": "monthly",
            "max_stores": 1,
            "max_products": 50,
            "max_monthly_orders": 100,
            "has_analytics": False,
            "has_email_support": False,
            "has_priority_support": False,
            "has_custom_domain": False,
            "has_api_access": False,
            "has_integrations": False,
            "commission_percentage": Decimal("5.00"),
            "is_active": True,
            "is_featured": False,
            "order": 0,
        },
    )

    SubscriptionPlan.objects.get_or_create(
        slug="basic",
        defaults={
            "name": "Базовий",
            "description": "Для зростаючого бізнесу. Розширені можливості та підтримка.",
            "price": Decimal("299.00"),
            "billing_cycle": "monthly",
            "max_stores": 3,
            "max_products": 500,
            "max_monthly_orders": 1000,
            "has_analytics": True,
            "has_email_support": True,
            "has_priority_support": False,
            "has_custom_domain": False,
            "has_api_access": False,
            "has_integrations": True,
            "commission_percentage": Decimal("3.00"),
            "is_active": True,
            "is_featured": True,
            "order": 1,
        },
    )

    SubscriptionPlan.objects.get_or_create(
        slug="premium",
        defaults={
            "name": "Преміум",
            "description": "Максимальні можливості для великого бізнесу. Без обмежень.",
            "price": Decimal("799.00"),
            "billing_cycle": "monthly",
            "max_stores": 10,
            "max_products": 10000,
            "max_monthly_orders": 99999,
            "has_analytics": True,
            "has_email_support": True,
            "has_priority_support": True,
            "has_custom_domain": True,
            "has_api_access": True,
            "has_integrations": True,
            "commission_percentage": Decimal("1.00"),
            "is_active": True,
            "is_featured": False,
            "order": 2,
        },
    )


def reverse_seed(apps, schema_editor):
    SubscriptionPlan = apps.get_model("core", "SubscriptionPlan")
    SubscriptionPlan.objects.filter(slug__in=["free", "basic", "premium"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_planfeature_subscriptionplan_usersubscription_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_plans, reverse_seed),
    ]
